### ISSUE TITLE
Some misleading @copyright tags

### ISSUE THREAD

**Issue by mudrd8mz** [webers-technikum-wien/moodle-qformat_printout#2]
The following copyright tags

lang/en/qformat_printout.php: * @copyright  2010 Helen Foster
classes/privacy/provider.php: * @copyright  2018 Andrew Nicols <andrew@nicols.co.uk>

Are a bit misleading. Please refer to https://docs.moodle.org/dev/Plugin_contribution_checklist#Copyrights

**Comment by stemiwe** [comment]
fixed
